// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

namespace odb
{
  // Entity
  //

  inline
  access::object_traits< ::db::Entity >::id_type
  access::object_traits< ::db::Entity >::
  id (const object_type& o)
  {
    return o.id;
  }

  inline
  void access::object_traits< ::db::Entity >::
  callback (database& db, object_type& x, callback_event e)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (x);
    ODB_POTENTIALLY_UNUSED (e);
  }

  inline
  void access::object_traits< ::db::Entity >::
  callback (database& db, const object_type& x, callback_event e)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (x);
    ODB_POTENTIALLY_UNUSED (e);
  }
}

#include <odb/details/unique-ptr.hxx>

namespace odb
{
  // Entity
  //

  inline
  void access::object_traits_impl< ::db::Entity, id_mssql >::
  load_ (statements_type& sts,
         object_type& obj,
         bool)
  {
    ODB_POTENTIALLY_UNUSED (sts);
    ODB_POTENTIALLY_UNUSED (obj);
  }

  inline
  access::object_traits_impl< ::db::Entity, id_mssql >::root_traits::image_type&
  access::object_traits_impl< ::db::Entity, id_mssql >::
  root_image (image_type& i)
  {
    return i;
  }

  inline
  access::object_traits_impl< ::db::Entity, id_mssql >::image_type*
  access::object_traits_impl< ::db::Entity, id_mssql >::
  clone_image (image_type& i)
  {
    return new image_type (i);
  }

  inline
  void access::object_traits_impl< ::db::Entity, id_mssql >::
  copy_image (image_type& d, image_type& s)
  {
    d = s;
  }

  inline
  void access::object_traits_impl< ::db::Entity, id_mssql >::
  free_image (image_type* i)
  {
    delete i;
  }
}

