/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

IF OBJECT_ID('City_id_fk', 'F') IS NOT NULL
  ALTER TABLE [City]
    DROP CONSTRAINT [City_id_fk];
GO

IF OBJECT_ID('City', 'U') IS NOT NULL
  DROP TABLE [City];
GO

CREATE TABLE [City] (
  [id] INT NOT NULL PRIMARY KEY,
  [placeID] VARCHAR(512) NULL,
  [formatedAddress] VARCHAR(512) NULL,
  [location_lat] FLOAT NOT NULL,
  [location_lng] FLOAT NOT NULL);
GO

ALTER TABLE [City]
  ADD CONSTRAINT [City_id_fk]
    FOREIGN KEY ([id])
    REFERENCES [Entity] ([id])
    ON DELETE CASCADE;
GO

