/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

IF OBJECT_ID('Credentials_id_fk', 'F') IS NOT NULL
  ALTER TABLE [Credentials]
    DROP CONSTRAINT [Credentials_id_fk];
GO

IF OBJECT_ID('Credentials', 'U') IS NOT NULL
  DROP TABLE [Credentials];
GO

CREATE TABLE [Credentials] (
  [id] INT NOT NULL PRIMARY KEY,
  [role] INT NOT NULL,
  [login] VARCHAR(512) NULL,
  [password] VARCHAR(512) NULL);
GO

ALTER TABLE [Credentials]
  ADD CONSTRAINT [Credentials_id_fk]
    FOREIGN KEY ([id])
    REFERENCES [Entity] ([id])
    ON DELETE CASCADE;
GO

