// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

namespace odb
{
}

namespace odb
{
  // Location
  //

  inline
  bool access::composite_value_traits< ::Location, id_mssql >::
  get_null (const image_type& i)
  {
    bool r (true);
    r = r && i.lat_size_ind == SQL_NULL_DATA;
    r = r && i.lng_size_ind == SQL_NULL_DATA;
    return r;
  }

  inline
  void access::composite_value_traits< ::Location, id_mssql >::
  set_null (image_type& i,
            mssql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mssql;

    i.lat_size_ind = SQL_NULL_DATA;
    i.lng_size_ind = SQL_NULL_DATA;
  }
}

