// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef LOCATION_ODB_H
#define LOCATION_ODB_H

// Begin prologue.
//
#include <odb/qt/version.hxx>
#if ODB_QT_VERSION != 2040000 // 2.4.0
#  error ODB and C++ compilers see different libodb-qt interface versions
#endif
#include <odb/qt/basic/mssql/qstring-traits.hxx>
#include <odb/qt/basic/mssql/qbyte-array-traits.hxx>
#include <odb/qt/basic/mssql/quuid-traits.hxx>
#include <odb/qt/containers/qhash-traits.hxx>
#include <odb/qt/containers/qlist-traits.hxx>
#include <odb/qt/containers/qlinked-list-traits.hxx>
#include <odb/qt/containers/qmap-traits.hxx>
#include <odb/qt/containers/qset-traits.hxx>
#include <odb/qt/containers/qvector-traits.hxx>
#include <odb/qt/date-time/mssql/qdate-traits.hxx>
#include <odb/qt/date-time/mssql/qtime-traits.hxx>
#include <odb/qt/date-time/mssql/qdate-time-traits.hxx>
#include <QtCore/QSharedPointer>
#include <odb/qt/smart-ptr/pointer-traits.hxx>
#include <odb/qt/smart-ptr/wrapper-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "Model/Location.h"

#include "Database/Mapping/Entity-odb.h"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/session.hxx>
#include <odb/cache-traits.hxx>
#include <odb/result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
}

#include <odb/details/buffer.hxx>

#include <odb/mssql/version.hxx>
#include <odb/mssql/forward.hxx>
#include <odb/mssql/binding.hxx>
#include <odb/mssql/mssql-types.hxx>
#include <odb/mssql/query.hxx>

namespace odb
{
  // Location
  //
  template <>
  class access::composite_value_traits< ::Location, id_mssql >
  {
    public:
    typedef ::Location value_type;

    struct image_type
    {
      // lat
      //
      double lat_value;
      SQLLEN lat_size_ind;

      // lng
      //
      double lng_value;
      SQLLEN lng_size_ind;
    };

    static void
    bind (mssql::bind*,
          image_type&,
          mssql::statement_kind);

    static void
    init (image_type&,
          const value_type&,
          mssql::statement_kind);

    static void
    init (value_type&,
          const image_type&,
          database*);

    static bool
    get_null (const image_type&);

    static void
    set_null (image_type&,
              mssql::statement_kind);

    static const std::size_t column_count = 2UL;
  };
}

#include "Location-odb-inl.h"

#include <odb/post.hxx>

#endif // LOCATION_ODB_H
