/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

IF OBJECT_ID('Route_stops_value_fk', 'F') IS NOT NULL
  ALTER TABLE [Route_stops]
    DROP CONSTRAINT [Route_stops_value_fk];
GO

IF OBJECT_ID('Route_id_fk', 'F') IS NOT NULL
  ALTER TABLE [Route]
    DROP CONSTRAINT [Route_id_fk];
GO

IF OBJECT_ID('RouteInfo_id_fk', 'F') IS NOT NULL
  ALTER TABLE [RouteInfo]
    DROP CONSTRAINT [RouteInfo_id_fk];
GO

IF OBJECT_ID('RouteInfo_origin_fk', 'F') IS NOT NULL
  ALTER TABLE [RouteInfo]
    DROP CONSTRAINT [RouteInfo_origin_fk];
GO

IF OBJECT_ID('RouteInfo_destination_fk', 'F') IS NOT NULL
  ALTER TABLE [RouteInfo]
    DROP CONSTRAINT [RouteInfo_destination_fk];
GO

IF OBJECT_ID('Route_stops', 'U') IS NOT NULL
  DROP TABLE [Route_stops];
GO

IF OBJECT_ID('Route', 'U') IS NOT NULL
  DROP TABLE [Route];
GO

IF OBJECT_ID('RouteInfo', 'U') IS NOT NULL
  DROP TABLE [RouteInfo];
GO

CREATE TABLE [RouteInfo] (
  [id] INT NOT NULL PRIMARY KEY,
  [origin] INT NULL,
  [destination] INT NULL,
  [totalDistance] FLOAT NOT NULL);
GO

CREATE TABLE [Route] (
  [id] INT NOT NULL PRIMARY KEY,
  [info] INT NULL,
  [polyline] VARCHAR(512) NULL
  /*
  CONSTRAINT [Route_info_fk]
    FOREIGN KEY ([info])
    REFERENCES [RouteInfo] ([id])
  */);
GO

CREATE TABLE [Route_stops] (
  [object_id] INT NOT NULL,
  [index] INT NOT NULL,
  [value] INT NULL,
  CONSTRAINT [Route_stops_object_id_fk]
    FOREIGN KEY ([object_id])
    REFERENCES [Route] ([id])
    ON DELETE CASCADE);
GO

CREATE INDEX [object_id_i]
  ON [Route_stops] ([object_id]);
GO

CREATE INDEX [index_i]
  ON [Route_stops] ([index]);
GO

ALTER TABLE [RouteInfo]
  ADD CONSTRAINT [RouteInfo_id_fk]
    FOREIGN KEY ([id])
    REFERENCES [Entity] ([id])
    ON DELETE CASCADE
      /*
      CONSTRAINT [RouteInfo_origin_fk]
    FOREIGN KEY ([origin])
    REFERENCES [City] ([id])
      */
      /*
      CONSTRAINT [RouteInfo_destination_fk]
    FOREIGN KEY ([destination])
    REFERENCES [City] ([id])
      */;
GO

ALTER TABLE [Route]
  ADD CONSTRAINT [Route_id_fk]
    FOREIGN KEY ([id])
    REFERENCES [Entity] ([id])
    ON DELETE CASCADE;
GO

/*
ALTER TABLE [Route_stops]
  ADD CONSTRAINT [Route_stops_value_fk]
    FOREIGN KEY ([value])
    REFERENCES [City] ([id])
*/

