// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

namespace odb
{
  // User
  //

  inline
  access::object_traits< ::User >::id_type
  access::object_traits< ::User >::
  id (const object_type& o)
  {
    return object_traits< ::db::Entity >::id (o);
  }

  inline
  void access::object_traits< ::User >::
  callback (database& db, object_type& x, callback_event e)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (x);
    ODB_POTENTIALLY_UNUSED (e);
  }

  inline
  void access::object_traits< ::User >::
  callback (database& db, const object_type& x, callback_event e)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (x);
    ODB_POTENTIALLY_UNUSED (e);
  }
}

namespace odb
{
  // User
  //

  inline
  void access::object_traits_impl< ::User, id_mssql >::
  bind (mssql::bind* b, id_image_type& i, bool bv)
  {
    object_traits_impl< ::db::Entity, id_mssql >::bind (b, i, bv);
  }

  inline
  void access::object_traits_impl< ::User, id_mssql >::
  init (id_image_type& i, const id_type& id, const version_type* v)
  {
    object_traits_impl< ::db::Entity, id_mssql >::init (i, id, v);
  }

  inline
  bool access::object_traits_impl< ::User, id_mssql >::
  check_version (const std::size_t* v, const image_type& i)
  {
    return 
      v[0UL] != i.version ||
      v[1UL] != i.base->version;
  }

  inline
  void access::object_traits_impl< ::User, id_mssql >::
  update_version (std::size_t* v, const image_type& i, mssql::binding* b)
  {
    v[0UL] = i.version;
    v[1UL] = i.base->version;
    b[0UL].version++;
    b[1UL].version++;
  }
}

